# Generated by Django 3.1.1 on 2020-10-13 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shippingaddrss',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
